dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - lua5.1
    - gnuplot
    - gcc-multilib
install:
 - opam init -j 2 --compiler=4.02.3 -n -y
 - eval $(opam config env)
 - opam config var root
 - opam install -j 2 -y camlp5 ocamlfind ppx_tools_versioned ppx_deriving ocaml-migrate-parsetree
 - opam list
script:
 - make
 - make -C bench
